@startuml
participant "Utilisateur" as usr
participant "Autre\nutilisateurs connéctés" as cousr

group sending a message
    usr -> cousr : sendMsg
    cousr -> cousr: checkPackets
    alt if packet gets recieved
        cousr -> cousr : getsNotified
    end
    cousr -> usr : DidReccieveMessage
end
group recieving a message
    cousr -> usr : sendMsg
    usr -> usr: checkPackets
    alt if packet gets recieved
        usr -> usr : getsNotified
    end
    usr -> cousr : DidReccieveMessage
end
@enduml