@startuml
participant "Utilisateur" as usr
participant "Autre\nutilisateurs connéctés" as cousr
[-> usr : connection 
usr -> cousr : pingConnection
loop for n user connected
    alt [checkIfAlreadyRecieved == false]
        cousr -> usr  : pingBackHello
        usr -> usr : recordPingRecieve
    else
        cousr -> cousr : AlreadyRecieved = true()
    end 
end
@enduml