@startuml
participant "Utilisateur" as usr
participant "Autre\nutilisateurs connéctés" as cousr
alt local user disconnection
usr -> cousr : pingDisconnection
[<-  usr : disconnect
end

alt distant user disconnection
    cousr -> usr : pingDisconnection
    usr -> usr : deleteUserFromList
end
@enduml
