@startuml
left to right direction
actor utilisateur as u

package chat{
usecase "connect" as uc1
usecase "enter username" as uc2
  usecase "send message/file to a connected user/group" as uc3
usecase "receive message/file" as uc4
usecase "consult the liste" as uc5
usecase "disconnect" as uc6
usecase "send log status" as uc7
usecase "get notified" as uc8

u ---> uc1
uc1 <.. uc7 : "include"
uc6 <.. uc7 : "include"
uc6 ..> uc1 : "include"
uc1 <.. uc2 : "include"
uc1 ..> uc3 : "extend"
uc1 ..> uc4 : "extend"
uc1 ..> uc5 : "extend"
uc1 ..> uc8 : "extend"
}

@enduml